name: ${project.name}
main: net.azisaba.builders.worldeditlimiter.WorldEditLimiter
version: ${project.version}
description: ${project.description}
author: siloneco
depend: [ "WorldEdit" ]
api-version: 1.13